In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('../store/comque_new.csv')

df.head()

,ID,type_of_food,name_of_food,how_to_prepare,main_ingredients,taste,outstanding_fragrance,current_price,number_of_people_eating
0,1,MÓN KHAI VỊ,Bánh xèo,"Đổ bột gạo pha nước cốt dừa, chiên vàng giòn c...","Bột gạo, tôm, thịt ba chỉ, giá đỗ,...",Đồ béo,Thơm và béo của nước cốt dừa hoà quyện cùng to...,"145,000",2-3 người
1,2,MÓN KHAI VỊ,Bánh khọt nước dừa,"Đổ bột gạo pha nước cốt dừa vào khuôn nhỏ, chi...","Bột gạo, nước cốt dừa, tôm",Đồ béo,Thơm và béo của nước cốt dừa hoà quyện cùng to...,"145,000",2-3 người
2,3,MÓN KHAI VỊ,Hến xúc bánh đa,"Hến xào hành, rau răm, ăn kèm bánh đa","Hến, rau răm, bánh đa","Đồ mặn, cay","Vị ngọt béo tự nhiên của hến, cay nhẹ của ớt v...","155,000",1-2 người
3,4,MÓN KHAI VỊ,Mực chiên giòn,"Mực tẩm bột chiên xù, chiên vàng","Mực, bột chiên",Đồ béo,"Mực tươi, béo của bột chiên giòn","175,000",2-3 người
4,5,MÓN KHAI VỊ,Cơm cháy mỡ hành chà bông,"Cơm cháy chiên giòn, rưới mỡ hành, rắc chà bông","Gạo, chà bông, hành lá",Đồ mặn,"Thơm mỡ hành, chà bông","150,000",2-3 người

# TOOL 1

In [4]:
def type_values_in_type_of_food(df: pd.DataFrame) -> list[list]:
    """_summary_

    Args:
        df (pd.DataFrame): _description_

    Returns:
        list[list]: _description_
    """
    vals_counts = df["type_of_food"].value_counts()
    return np.column_stack(([name.lower() for name in vals_counts.index.tolist()], vals_counts.values.tolist())).tolist()

np.array(type_values_in_type_of_food(df))[::,0]

array(['món cá', 'món khai vị', 'món ăn chơi', 'món rau', 'món gỏi',
       'món gà, vịt & trứng', 'món tôm & mực', 'món xào',
       'nước mát nhà làm', 'lẩu', 'món thịt', 'món sườn & đậu hũ',
       'món canh', 'các loại khô', 'tráng miệng'], dtype='<U19')

# TOOL 2

In [3]:
def search_values_in_type(df: pd.DataFrame, name_col: str) -> list[list]:
    """_summary_

    Args:
        df (pd.DataFrame): _description_
        name_col (str): _description_

    Returns:
        list[list]: _description_
    """
    vals_counts = df[name_col].value_counts()
    return np.column_stack(([name.lower() for name in vals_counts.index.tolist()], vals_counts.values.tolist())).tolist()

search_values_in_type(df, name_col="name_of_food")

[['mực chiên giòn', '2'],
 ['bánh xèo', '1'],
 ['bánh khọt nước dừa', '1'],
 ['hến xúc bánh đa', '1'],
 ['cơm cháy mỡ hành chà bông', '1'],
 ['sụn gà rang muối', '1'],
 ['chả mực hạ long', '1'],
 ['ốc bươu nhồi thịt', '1'],
 ['sụn gà chiên nước mắm', '1'],
 ['tôm bọc cốm xanh', '1'],
 ['chả giò hải sản', '1'],
 ['cơm cháy chảo kho quẹt', '1'],
 ['bánh hỏi heo quay', '1'],
 ['xôi chiên chà bông', '1'],
 ['bắp giò heo rút xương lên mẹt', '1'],
 ['chả cá lên mẹt', '1'],
 ['gân bò xào cần', '1'],
 ['nem nướng lên mẹt', '1'],
 ['bò viên nước lèo', '1'],
 ['bò viên gân chiên', '1'],
 ['chả giò tôm đất', '1'],
 ['ếch chiên nước mắm', '1'],
 ['dồi sụn chấm mắm tôm', '1'],
 ['salad dầu giấm', '1'],
 ['bò trộn salad', '1'],
 ['gỏi mực chua cay', '1'],
 ['gỏi cuốn tôm thịt', '1'],
 ['gỏi dưa leo tôm khô', '1'],
 ['gỏi tôm sốt thái', '1'],
 ['gỏi gà bắp chuối', '1'],
 ['gỏi xoài tôm khô', '1'],
 ['gỏi ngó sen tôm thịt', '1'],
 ['gỏi cuốn bò áp chảo', '1'],
 ['thịt kho tiêu', '1'],
 ['thịt kho trứng', '1'],
 ['ba rọi cháy cạnh', '1'],
 ['thịt luộc cà pháo mắm tôm', '1'],
 ['mắm chưng', '1'],
 ['ba rọi mắm ruốc', '1'],
 ['ba rọi rim dừa', '1'],
 ['cá lóc kho tộ', '1'],
 ['cá basa kho tộ', '1'],
 ['cá thu kho tộ', '1'],
 ['cá trứng chiên mắm me', '1'],
 ['cá bống trứng kho tiêu', '1'],
 ['cá bớp kho tộ', '1'],
 ['cá trê chiên mắm xoài', '1'],
 ['cá diêu hồng chiên xù cuốn bánh tráng', '1'],
 ['cá sặc trộn xoài', '1'],
 ['mắm kho miền tây', '1'],
 ['cá thu chiên mắm xoài', '1'],
 ['cá ngừ kho thơm', '1'],
 ['cá nục kho khô', '1'],
 ['cá nục kho măng', '1'],
 ['cá điêu hồng chiên sốt cà', '1'],
 ['cá thu sốt cà', '1'],
 ['khô cá đù', '1'],
 ['khô cá dứa', '1'],
 ['khô cá lóc', '1'],
 ['mực xào chua ngọt', '1'],
 ['mực ống nhồi thịt', '1'],
 ['mực chiên nước mắm', '1'],
 ['mực trứng hấp gừng', '1'],
 ['tôm rim mặn', '1'],
 ['tôm rim', '1'],
 ['tép rong rang khế', '1'],
 ['tôm rang muối cay', '1'],
 ['sườn xào chua ngọt', '1'],
 ['sườn ram mặn', '1'],
 ['sườn cọng chiên muối ớt', '1'],
 ['đậu hủ nhồi thịt sốt cà', '1'],
 ['đậu hủ chiên giòn chấm mắm tôm', '1'],
 ['gà tre hấp mắm nhĩ', '1'],
 ['gà kho gừng', '1'],
 ['gà sả ớt', '1'],
 ['cánh gà chiên nước mắm', '1'],
 ['vịt kho gừng', '1'],
 ['trứng chiên thịt', '1'],
 ['trứng chiên hến', '1'],
 ['trứng chiên cà chua', '1'],
 ['trứng chiên hành', '1'],
 ['bò xào rau muống', '1'],
 ['bò xào bí nụ', '1'],
 ['bò xào cải thìa', '1'],
 ['đọt su xào bò', '1'],
 ['bò xào cải ngồng', '1'],
 ['bò xào hành cần', '1'],
 ['cải bó xôi xào bò', '1'],
 ['bông hẹ xào bò', '1'],
 ['cải thìa xào nấm đông cô', '1'],
 ['rau luộc thập cẩm kho quẹt', '1'],
 ['cải ngồng xào dầu hào', '1'],
 ['khổ qua xào trứng', '1'],
 ['nụ bí xào tỏi', '1'],
 ['rau muống xào tỏi', '1'],
 ['đọt su xào tỏi', '1'],
 ['cải bó xôi xào tỏi', '1'],
 ['đậu bắp luộc chấm chao', '1'],
 ['rau muống xào chao', '1'],
 ['bông hẹ xào tỏi', '1'],
 ['canh diêu hồng nấu ngót', '1'],
 ['canh cá bóp măng chua', '1'],
 ['canh tần ô cá thác lác/ thịt bằm', '1'],
 ['canh chua cá hú', '1'],
 ['lẩu cá thì là', '1'],
 ['lẩu cá thác lác', '1'],
 ['lẩu cua đồng', '1'],
 ['lẩu ếch lá giang', '1'],
 ['lẩu cá bớp', '1'],
 ['lẩu mắm', '1'],
 ['lẩu dượng bầu', '1'],
 ['chè đậu xanh đánh', '1'],
 ['sương sa sương sáo hột é', '1'],
 ['sương sa hạt lựu', '1'],
 ['củ sen', '1'],
 ['trà hoa cúc mật ong', '1'],
 ['nước sâm', '1'],
 ['trà tắc', '1'],
 ['trà đá', '1'],
 ['coca/ 7 up', '1'],
 ['nước suối', '1'],
 ['bia các loại (tiger, heineken, saigon)', '1']]

In [12]:
search_values_in_type(df, name_col="how_to_prepare")

[['cá bớp nấu lẩu chua ngọt với rau', '2'],
 ['đổ bột gạo pha nước cốt dừa, chiên vàng giòn cùng topping', '1'],
 ['hến xào hành, rau răm, ăn kèm bánh đa', '1'],
 ['mực tẩm bột chiên xù, chiên vàng', '1'],
 ['cơm cháy chiên giòn, rưới mỡ hành, rắc chà bông', '1'],
 ['sụn gà chiên giòn, rang với muối hong kong', '1'],
 ['mực giã tay, chiên vàng', '1'],
 ['ốc bươu nhồi thịt băm, hấp sả', '1'],
 ['sụn gà chiên giòn, sốt nước mắm tỏi ớt', '1'],
 ['đổ bột gạo pha nước cốt dừa vào khuôn nhỏ, chiên giòn cùng topping', '1'],
 ['hải sản băm cuốn bánh tráng, chiên vàng', '1'],
 ['cơm chiên phồng, ăn kèm kho quẹt tôm khô', '1'],
 ['heo quay da giòn ăn cùng bánh hỏi và rau sống, nước mắm', '1'],
 ['xôi chiên phồng, rắc chà bông', '1'],
 ['giò heo rút xương hấp và thái lát, ăn cùng rau sống và mắm nêm', '1'],
 ['cá quết nhuyễn, chiên vàng', '1'],
 ['gân bò xào với cần tây, tỏi', '1'],
 ['nem nướng than hoa, ăn kèm rau', '1'],
 ['bò viên nấu cùng nước hầm xương', '1'],
 ['bò viên gân chiên giòn', '1'],
 ['tôm đất cuốn bánh tráng, chiên vàng', '1'],
 ['ếch chiên giòn, sốt nước mắm ', '1'],
 ['dồi sụn nướng, ăn kèm rau sống và mắm tôm', '1'],
 ['rau củ tươi rửa sạch, cắt nhỏ, trộn đều với nước sốt pha từ dầu ăn, giấm, đường muối và tiêu',
  '1'],
 ['thịt bò áp chảo hoặc luộc tái, cắt lát mỏng, trộn cùng rau xà lách, cà chua, hành tây và sốt dầu giấm.',
  '1'],
 ['tôm quết bột, bọc cốm xanh, chiên giòn', '1'],
 ['tôm luộc bóc vỏ, thịt heo ba chỉ luộc thái mỏng, cuốn chung với bún, rau thơm và bánh tráng mỏng',
  '1'],
 ['dưa leo bào sợi, trộn cùng tôm khô đã ngâm mềm, hành phi, rau thơm và nước mắm pha chua ngọt.',
  '1'],
 ['tôm (sống hoặc chín) trộn cùng nước sốt thái (chua cay mặn ngọn)', '1'],
 ['thịt gà xé nhỏ, trộn với bắp chuối bào sợi, rau thơm, hành phi, lạc rang và nước mắm chua ngọt.',
  '1'],
 ['xoài xanh bào sợi, trộn với tôm khô rang, rau răm, ớt, đậu phộng rang và nước mắm chua ngọt.',
  '1'],
 ['ngó sen chẻ nhỏ, trộn cùng tôm luộc, thịt ba chỉ, cà rốt, hành tây, rau răm và nước mắm chua ngọt.',
  '1'],
 ['bò thái lát mỏng, ướp gia vị rồi áp chảo, cuốn với bún, rau sống và bánh tráng mỏng. ăn kèm nước chấm chua ngọt hoặc sốt tương',
  '1'],
 ['thịt heo thái miếng vừa, ướp nước mắm, đường, tiêu rồi kho đến khi thấm gia vị',
  '1'],
 ['thịt ba rọi cắt miếng, ướp nước mắm, đường, kho chung với trứng vịt hoặc trứng cút cho đến khi thấm màu và mềm',
  '1'],
 ['ba rọi chiên áp cảo cho cạnh vàng giòn. thêm gia vị mắm, đường, tiêu', '1'],
 ['thịt ba rọi luộc chín, thái lát mỏng, ăn kèm cà pháo muối chua giòn và mắm tôm pha chanh, đường, ớt.',
  '1'],
 ['thịt ba rọi băm nhỏ, trộn chung với mắm. ăn kèm rau sống', '1'],
 ['thịt ba rọi xào hoặc rim với mắm ruốc, thêm sả, ớt để khử mùi và tạo vị',
  '1'],
 ['ba rọi kho/rim với nước dừa tươi', '1'],
 ['cá lóc cắt khúc, ướp mắm, tiêu, đường, kho trong nồi đất đến khi thấm vị',
  '1'],
 ['cá basa béo, kho cùng nước mắm, đường, tiêu đến khi nước sánh', '1'],
 ['cá thu cắt khoanh, ướp gia vị, kho trong nồi đất cho săn', '1'],
 ['cá trứng chiên giòn, chan sốt me chua ngọt mặn cay', '1'],
 ['cá bống trứng kho tiêu', '1'],
 ['cá bớp cắt khúc, kho nước mắm đường, thêm hành tỏi và tiêu', '1'],
 ['cá trê chiên giòn, rưới sốt mắm pha xoài băm chua ngọt', '1'],
 ['cá diêu hồng chiên xù nguyên con, ăn kèm bánh tráng, bún và rau sống, chấm nước mắm chua ngọt',
  '1'],
 ['cá sặc phơi khô chiên giòn, xé nhỏ, trộn với xoài xanh bào, rau thơm, nước mắm chua ngọt',
  '1'],
 ['mắm miền tây nấu với nước, thêm thịt ba rọi, tôm, cà tím, rau ăn kèm (rau đắng, bông súng, rau muống…)',
  '1'],
 ['cá thu cắt khoanh chiên vàng, rưới sốt mắm xoài chua ngọt cay', '1'],
 ['cá ngừ kho cùng thơm (dứa), hành tỏi, gia vị mắm đường.', '1'],
 ['cá nục kho liu riu với mắm, đường, tiêu đến khi cạn sệt', '1'],
 ['cá nục kho cùng măng chua, gia vị mắm, đường, ớt', '1'],
 ['cá điêu hồng chiên vàng, rưới sốt cà chua xào hành tỏi', '1'],
 ['cá thu cắt khoanh, chiên sơ, rim cùng sốt cà chua', '1'],
 ['khô cá đù chiên', '1'],
 ['mực luộc chín vừa, cắt khoanh; trộn với hành tây, cà rốt, rau răm, ớt và nước mắm pha chua ngọt.',
  '1'],
 ['khô cá dứa chiên', '1'],
 ['khô cá lóc chiên', '1'],
 ['mực xào cùng ớt chuông, dứa, hành tây', '1'],
 ['mực tẩm bột, chiên vàng giòn', '1'],
 ['mực chiên giòn, sốt nước mắm tỏi ớt', '1'],
 ['mực trứng hấp cùng gừng và hành', '1'],
 ['tôm rim cùng nước mắm, đường', '1'],
 ['mực nhồi thịt băm rồi chiên vàng', '1'],
 ['tép nhỏ rang khô với khế chua', '1'],
 ['tôm chiên giòn, rang muối ớt', '1'],
 ['sườn non chiên vàng, xào chua ngọt', '1'],
 ['sườn ram với nước mắm, đường', '1'],
 ['sườn chiên giòn, rang muối ớt', '1'],
 ['đậu hủ nhồi thịt chiên, sốt cà chua', '1'],
 ['đậu hủ chiên vàng giòn, chấm mắm tôm', '1'],
 ['tôm rim đường, nước màu', '1'],
 ['gà chặt miếng, ướp mắm, đường, kho cùng gừng thái sợi', '1'],
 ['gà chặt nhỏ, xào/kho với sả băm, ớt và gia vị', '1'],
 ['cánh gà chiên vàng, sau đó áo sốt mắm đường', '1'],
 ['thịt vịt chặt khúc, kho cùng gừng, mắm, đường cho săn', '1'],
 ['trứng gà đánh tan, trộn thịt băm, nêm gia vị, chiên vàng', '1'],
 ['trứng đánh tan, trộn hến xào sơ, chiên vàng', '1'],
 ['trứng chiên cùng cà chua thái hạt lựu hoặc xào cà chua trước rồi rưới trứng',
  '1'],
 ['trứng đánh tan, trộn hành lá thái nhỏ, chiên vàng', '1'],
 ['thịt bò ướp tỏi, xào nhanh với rau muống chần sơ', '1'],
 ['bò xào cùng hoa bí non, nêm gia vị vừa ăn', '1'],
 ['thịt bò xào cải thìa cắt khúc, nêm gia v', '1'],
 ['đọt su xào nhanh với thịt bò ướp tỏi', '1'],
 ['cải ngồng cắt khúc, xào nhanh với thịt bò', '1'],
 ['thịt bò xào cùng hành tây, cần tây cắt khúc', '1'],
 ['bò xào nhanh với cải bó xôi, nêm gia vị vừa', '1'],
 ['gà tre làm sạch, hấp cách thủy với mắm nhĩ nguyên chất, ăn kèm rau răm hoặc lá chanh',
  '1'],
 ['bông hẹ non xào nhanh với thịt bò', '1'],
 ['nấm đông cô ngâm mềm, xào cùng cải thìa với dầu hào', '1'],
 ['rau xào nhanh lửa lớn, nêm dầu hào', '1'],
 ['các loại rau luộc chín vừa, chấm kho quẹt tôm khô', '1'],
 ['khổ qua, trứng gà', '1'],
 ['rau muống xào nhanh lửa lớn với tỏi', '1'],
 ['đọt su giòn non, xào cùng tỏi', '1'],
 ['khổ qua cắt lát xào cùng trứng đánh', '1'],
 ['đậu bắp luộc, chấm với chao', '1'],
 ['rau muống xào chao đỏ', '1'],
 ['bông hẹ xào chín tới với tỏ', '1'],
 ['cá diêu hồng nấu với cà chua, thì là, cần tàu', '1'],
 ['cá bóp nấu măng chua, cà chua, me', '1'],
 ['cá thác lác quết hoặc thịt bằm nấu với rau tần ô', '1'],
 ['cá hú nấu với bạc hà, cà chua, me chua', '1'],
 ['rau xào nhanh giữ màu xanh', '1'],
 ['cá nấu lẩu với cà chua, thì là, hành', '1'],
 ['cá thác lác quết thả vào nồi lẩu rau', '1'],
 ['cua đồng nấu riêu, ăn cùng rau sống', '1'],
 ['ếch xào sơ, nấu lẩu với lá giang', '1'],
 ['lẩu cá linh, cá lóc… với bông điên điển, rau đồng', '1'],
 ['đậu xanh nấu chín, đánh nhuyễn với đường, có thể thêm nước cốt dừa', '1'],
 ['sương sa, sương sáo cắt miếng, trộn với hột é, đường, đá lạnh', '1'],
 ['hạt lựu (bột lọc nhuộm màu) luộc, ăn cùng sương sa và nước đường', '1'],
 ['củ sen tươi nấu với đường phèn, có thể thêm nhãn nhục', '1'],
 ['hoa cúc khô hãm trà, pha mật ong', '1'],
 ['các loại thảo mộc (mía lau, rễ tranh, la hán quả…) nấu lấy nước', '1'],
 ['nước trà xanh, pha với tắc, đường', '1'],
 ['trà nấu ', '1'],
 ['nước ngọt có gas', '1'],
 ['nước suối thanh lọc', '1'],
 ['bia các loại', '1']]

In [13]:
search_values_in_type(df, name_col="main_ingredients")

[['mực, bột chiên', '2'],
 ['cá nục, măng chua, nước mắm, ớt', '2'],
 ['bột gạo, tôm, thịt ba chỉ, giá đỗ,...', '1'],
 ['hến, rau răm, bánh đa', '1'],
 ['bột  gạo, nước cốt dừa, tôm', '1'],
 ['sụn gà, bột muối rang', '1'],
 ['mực, gia vị', '1'],
 ['ốc bươu, thịt băm, sả', '1'],
 ['gạo, chà bông, hành lá', '1'],
 ['tôm tươi, cốm xanh', '1'],
 ['hải sản băm, bánh tráng', '1'],
 ['cơm, tôm khô, thịt ba chỉ, chà bông', '1'],
 ['heo quay, bánh hỏi, rau sống, nước mắm chua ngọt', '1'],
 ['gạo nếp, chà bông', '1'],
 ['giò heo, rau và mắm ăn kèm', '1'],
 ['cá, thì là, gia vị', '1'],
 ['gân bò, cần tây', '1'],
 ['thịt heo xay, gia vị', '1'],
 ['bò viên, nước hầm xương', '1'],
 ['bò viên gân', '1'],
 ['tôm đất, bánh tráng', '1'],
 ['thịt ếch, nước mắm', '1'],
 ['thịt heo, sụn, mắm tôm', '1'],
 ['rau xà lách, dưa leo, cà chua, hành tây, dầu ăn, giấm, đường, tiêu.', '1'],
 ['sụn gà, nước mắm', '1'],
 ['thịt bò, xà lách, cà chua, hành tây, dầu giấm', '1'],
 ['mực tươi, hành tây, cà rốt, rau răm, ớt, nước mắm – chanh – đường.', '1'],
 ['dưa leo, tôm khô, hành phi, rau thơm', '1'],
 ['tôm, thịt heo, bún, rau sống, bánh tráng', '1'],
 ['thịt gà, bắp chuối, rau thơm, đậu phộng', '1'],
 ['xoài xanh, tôm khô, đậu phổng', '1'],
 ['ngó sen, tôm, thịt ba chỉ, rau răm', '1'],
 ['tôm tươi, ớt, chanh, nước sốt thái, xoài xanh', '1'],
 ['thịt heo, nước mắm, đường, tiêu', '1'],
 ['thịt ba rọi, trứng vịt, nước mắm, đường', '1'],
 ['thịt ba rọi, nước mắm, đường, tiêu', '1'],
 ['thịt ba rọi, cà pháo muối, mắm tôm', '1'],
 ['thịt ba rọi, mắm cá, ớt, sả, rau sống ăn kèm', '1'],
 ['thịt ba rọi, mắm ruốc, sả, ớt', '1'],
 ['thịt ba rọi, nước dừa, nước mắm, đường', '1'],
 ['thịt bò, bánh tráng, bún, rau sống', '1'],
 ['cá lóc, nước mắm, đường, tiêu, hành tỏi', '1'],
 ['cá basa, nước mắm, đường, tiêu', '1'],
 ['cá trứng, me, đường, ớt, nước mắm', '1'],
 ['cá thu, nước mắm, đường, tiêu', '1'],
 ['cá bớp, nước mắm, đường, tiêu, hành tỏi', '1'],
 ['cá trê, xoài xanh, nước mắm, đường, ớt', '1'],
 ['cá diêu hồng, bánh tráng, rau sống, nước mắm chua ngọt', '1'],
 ['cá bống trứng, nước mắm, đường, tiêu', '1'],
 ['cá sặc khô, xoài xanh, rau răm, ớt', '1'],
 ['mắm cá linh/cá sặc, thịt ba rọi, tôm', '1'],
 ['cá thu, xoài xanh, nước mắm, ớt', '1'],
 ['cá ngừ, thơm, nước mắm, hành tỏi', '1'],
 ['cá điêu hồng, cà chua, hành tỏi', '1'],
 ['cá thu, cà chua, hành tỏi', '1'],
 ['khô cá đù', '1'],
 ['khô cá dứa', '1'],
 ['khô cá lóc', '1'],
 ['mực, dứa, ớt chuông', '1'],
 ['mực ống, thịt heo băm', '1'],
 ['mực, nước mắm, tỏi', '1'],
 ['mực trứng, gừng, hành lá', '1'],
 ['tôm, nước mắm', '1'],
 ['tôm, đường, hành', '1'],
 ['tép rong, khế chua', '1'],
 ['tôm, muối, ớt', '1'],
 ['sườn heo, dứa, ớt chuông', '1'],
 ['sườn heo, nước mắm', '1'],
 ['sườn cọng, muối ớt', '1'],
 ['đậu hủ, thịt heo băm, cà chua', '1'],
 ['đậu hủ, mắm tôm', '1'],
 ['gà tre, mắm nhĩ, rau răm, lá chanh', '1'],
 ['gà, gừng, nước mắm', '1'],
 ['gà, sả, ớt, nước mắm', '1'],
 ['cánh gà, nước mắm, đường, tỏi', '1'],
 ['vịt, gừng, mắm, đường', '1'],
 ['trứng gà, thịt ba chỉ băm', '1'],
 ['trứng gà, hến', '1'],
 ['trứng, cà chua', '1'],
 ['trứng, hành lá', '1'],
 ['thịt bò, rau giòn xào', '1'],
 ['thịt bò, hoa bí', '1'],
 ['thịt bò, cải thìa', '1'],
 ['thịt bò, đọt su su, tỏi', '1'],
 ['bò, cải ngồng, tỏi', '1'],
 ['bò, hành tây, cần tây, tỏi', '1'],
 ['bò, cải bó xôi, tỏi', '1'],
 ['bò, bông hẹ, tỏi', '1'],
 ['cải thìa, nấm đông cô', '1'],
 ['rau củ (rau muống, bầu, cà rốt, đậu bắp…), kho quẹt', '1'],
 ['cải ngồng, dầu hào', '1'],
 ['khổ qua, trứng gà', '1'],
 ['nụ bí, tỏi', '1'],
 ['rau muống, tỏi', '1'],
 ['đọt su, tỏi', '1'],
 ['cải bó xôi, tỏi', '1'],
 ['đậu bắp, chao', '1'],
 ['rau muống, chao, tỏi', '1'],
 ['bông hẹ, tỏi', '1'],
 ['cá diêu hồng, cà chua, rau thơm', '1'],
 ['cá bóp, măng chua', '1'],
 ['tần ô, cá thác lác/thịt bằm', '1'],
 ['cá hú, rau canh chua', '1'],
 ['cá, thì là', '1'],
 ['cá thác lác, rau các loại', '1'],
 ['cua đồng, rau', '1'],
 ['thịt ếch, lá giang', '1'],
 ['cá bớp, cà chua, me', '1'],
 ['mắm, cá, rau sống miền tây', '1'],
 ['cá đồng, rau bông mùa nước nổi', '1'],
 ['đậu xanh, đường, nước cốt dừa', '1'],
 ['sương sa, sương sáo, hột é', '1'],
 ['hạt lựu bột lọc, sương sa', '1'],
 ['củ sen, đường phèn', '1'],
 ['hoa cúc, mật ong', '1'],
 ['thảo mộc, mía lau', '1'],
 ['trà, tắc', '1'],
 ['trà', '1'],
 ['nước ngọt', '1'],
 ['nước suối', '1'],
 ['vị lúa mạch', '1']]

In [14]:
search_values_in_type(df, name_col="taste")

[['đồ mặn', '60'],
 ['đồ béo', '7'],
 ['đồ béo, mặn', '6'],
 ['đồ chua ngọt', '5'],
 ['đồ ngọt', '4'],
 ['đồ mặn, chua nhẹ', '3'],
 ['đồ béo, mặn, chua ngọt', '3'],
 ['đồ mặn chua ngọt', '3'],
 ['đồ béo, mặn ngọt', '3'],
 ['đồ mặn, chua ngọt', '3'],
 ['đồ béo, ngọt', '3'],
 ['đồ mặn, béo nhẹ', '3'],
 ['đồ mặn, cay nhẹ', '2'],
 ['nước', '2'],
 ['đồ mặn, béo', '2'],
 ['đồ mặn, ngọt nhẹ', '2'],
 ['đồ mặn, béo ', '1'],
 ['đồ mặn, cay', '1'],
 ['đồ chua, cay, ngọt', '1'],
 ['đồ chua, ngọt', '1'],
 ['đồ chua cay', '1'],
 ['đồ chua, ngọt nhẹ', '1'],
 ['món mặn, chua ngọt nhẹ', '1'],
 ['đồ hấp', '1'],
 ['đồ mặn, chua', '1'],
 ['đồ ngọt béo, hơi chua', '1'],
 ['soft drink', '1'],
 ['beer', '1']]

In [15]:
search_values_in_type(df, name_col="outstanding_fragrance")

[['thơm và béo của nước cốt dừa hoà quyện cùng topping (tôm, thịt,..)', '2'],
 ['chao nồng, thoang thoảng tỏi', '2'],
 ['vị ngọt béo tự nhiên của hến, cay nhẹ của ớt và rau răm, tiêu', '1'],
 ['thơm mỡ hành, chà bông', '1'],
 ['mực tươi, béo của bột chiên giòn', '1'],
 ['mực tươi', '1'],
 ['ốc tươi, thơm sả, tiêu', '1'],
 ['thơm nước mắm tỏi ớt', '1'],
 ['thơm mùi muối rang', '1'],
 ['hải sản tươi', '1'],
 ['kho quẹt, mỡ hành', '1'],
 ['heo quay và mắm chua chua ngọt', '1'],
 ['nếp chiên. hành mỡ, chà bông', '1'],
 ['bắp giò tươi, mắm nêm thơm', '1'],
 ['cá chiên, thì là', '1'],
 ['gân bò, cần tây', '1'],
 ['thịt nướng', '1'],
 ['bò viên, nước hầm xương', '1'],
 ['thịt bò viên chiên', '1'],
 ['tôm chiên', '1'],
 ['ếch tươi, nước mắm', '1'],
 ['dồi sụn, mắm tôm', '1'],
 ['giấm chua thanh, tiêu xay, đôi khi có mùi thơm nhẹ từ dầu ô liu.', '1'],
 ['mùi thơm thịt bò áp chảo, thoảng mùi tiêu, hành tây sống', '1'],
 ['tôm tươi, cốm chiên thơm', '1'],
 ['rau thơm và thịt, tôm luộc', '1'],
 ['tôm khô, hành phi vàng giòn, rau thơm', '1'],
 ['vị ngọt của tôm và nước sốt thái cay nồng', '1'],
 ['thịt gà, hành phi, rau thơm', '1'],
 ['mùi tôm khô, rau răm, đậu phộng rang', '1'],
 ['hành phi giòn, rau răm, tôm thịt luộc', '1'],
 ['thịt bò áp chảo, rau thơm', '1'],
 ['mùi tiêu xay dậy lên trong nước kho, thơm nồng ấm.', '1'],
 ['thịt ba rọi kho, nước mắm', '1'],
 ['thịt cháy cạnh thơm lừng, quyện mùi mắm', '1'],
 ['thịt luộc, mùi đặc trưng của mắm tôm trộn cùng chanh ớt, hành phi', '1'],
 ['hương mắm kho đặc trưng', '1'],
 ['mùi mắm ruốc quyện với sả ớt, thơm nồng đặc trưng miền trung', '1'],
 ['vị mặn ngọt của nước dừa rim, thịt ba rọi đẫm sốt', '1'],
 ['mùi nước mắm kho quyện cùng với thịt cá', '1'],
 ['thịt cá basa quyện tiêu, nước mắm kho', '1'],
 ['cá thu kho', '1'],
 ['cá trứng chiên, nước mắm me chua ngọt', '1'],
 ['cá bống kho', '1'],
 ['cá bớp kho', '1'],
 ['cá trê chiên giòn, nước mắm xoài xanh', '1'],
 ['cá chiên giòn, rau thơm, nước mắm tỏi ớt', '1'],
 ['cá chiên thơm, rau răm, thoang thoảng mùi xoài xanh', '1'],
 ['hương mắm kho nồng nàng', '1'],
 ['cá chiên thơm, nước mắm xoài cay nồng', '1'],
 ['cá ngừ kho, thơm', '1'],
 ['cá nục kho, tiêu', '1'],
 ['cá nục kho cùng với măng', '1'],
 ['cá điêu hồng chiên sốt cà', '1'],
 ['cá thu sốt cà', '1'],
 ['khô cá đù', '1'],
 ['mùi cay nồng của ớt, rau răm', '1'],
 ['khô cá dứa', '1'],
 ['khô cá lóc', '1'],
 ['mực tươi, ớt chuông, dứa', '1'],
 ['mực tươi, bột chiên', '1'],
 ['nước mắm, mực tươi', '1'],
 ['mực trứng', '1'],
 ['tôm, nước mắm, tiêu', '1'],
 ['mực tươi, thịt heo', '1'],
 ['tép rang, khế', '1'],
 ['tôm, muối rang, ớt', '1'],
 ['sườn heo, ớt chuông, dứa', '1'],
 ['sườn heo, nước mắm, tiêu', '1'],
 ['sườn, ớt', '1'],
 ['cà chua chín, đậu hủ chiên', '1'],
 ['đậu hủ, mắm tôm', '1'],
 ['tôm rim', '1'],
 ['gà kho gừng nồng ấm', '1'],
 ['gà kho đậm mùi sả băm, thơm nồng mùi ớt', '1'],
 ['mùi nước mắm chiên, tỏi phi', '1'],
 ['gừng nồng, mùi vịt kho dậy mùi', '1'],
 ['trứng chiên vàng thơm, hành lá', '1'],
 ['trứng thơm, thoang thoảng vị hến', '1'],
 ['trứng chiên quyện sốt cà, mùi hành lá', '1'],
 ['hành lá quyện trứng chiên', '1'],
 ['thịt bò, rau muống', '1'],
 ['tỏi phi, mùi hoa bí non', '1'],
 ['tỏi phi, rau cải', '1'],
 ['tỏi phi, rau su su', '1'],
 ['tỏi phi, mùi cải ngồng đặc trưng.', '1'],
 ['thịt bò, hành tây, tỏi phi', '1'],
 ['tỏi phi, cải bó xôi chín', '1'],
 ['thịt gà ngọt, lớp da thơm nồng mùi mắm nhĩ', '1'],
 ['tỏi phi, mùi bông hẹ thoang thoảng hăng nhẹ', '1'],
 ['nấm đặc trưng, thoang thoảng dầu hào', '1'],
 ['dầu hào, tỏi phi', '1'],
 ['tôm khô, tiêu, tóp mỡ', '1'],
 ['khổ qua, trứng béo', '1'],
 ['rau muống, tỏi', '1'],
 ['đọt su, tỏi', '1'],
 ['trứng xào, khổ qua', '1'],
 ['thơm mùi tỏi', '1'],
 ['tỏi phi, hẹ non', '1'],
 ['thì là, cần tàu', '1'],
 ['măng chua, thịt cá ngọt, ngò gai', '1'],
 ['tần ô thơm, ngọt thanh', '1'],
 ['cá hú, ngò om, ngò gai', '1'],
 ['thì là nổi bật', '1'],
 ['rau thơm, thì là', '1'],
 ['gạch cua, hành phi', '1'],
 ['lá giang, sả', '1'],
 ['rau om, cần tàu', '1'],
 ['mắm cá, sả, ớt', '1'],
 ['rau đồng, mắm ruốc nhẹ', '1'],
 ['đậu xanh, dừa', '1'],
 ['hương lá sương sáo, nước đường, hột é', '1'],
 ['nước đường, lá dứa', '1'],
 ['sen, thoang thoảng nhãn nhục', '1'],
 ['hoa cúc thanh mát', '1'],
 ['thảo mộc nhẹ, mía lau', '1'],
 ['mùi trà và tắc', '1'],
 ['trà', '1'],
 ['gas', '1'],
 ['nước', '1'],
 ['bia', '1']]

In [16]:
search_values_in_type(df, name_col="outstanding_fragrance")

[['thơm và béo của nước cốt dừa hoà quyện cùng topping (tôm, thịt,..)', '2'],
 ['chao nồng, thoang thoảng tỏi', '2'],
 ['vị ngọt béo tự nhiên của hến, cay nhẹ của ớt và rau răm, tiêu', '1'],
 ['thơm mỡ hành, chà bông', '1'],
 ['mực tươi, béo của bột chiên giòn', '1'],
 ['mực tươi', '1'],
 ['ốc tươi, thơm sả, tiêu', '1'],
 ['thơm nước mắm tỏi ớt', '1'],
 ['thơm mùi muối rang', '1'],
 ['hải sản tươi', '1'],
 ['kho quẹt, mỡ hành', '1'],
 ['heo quay và mắm chua chua ngọt', '1'],
 ['nếp chiên. hành mỡ, chà bông', '1'],
 ['bắp giò tươi, mắm nêm thơm', '1'],
 ['cá chiên, thì là', '1'],
 ['gân bò, cần tây', '1'],
 ['thịt nướng', '1'],
 ['bò viên, nước hầm xương', '1'],
 ['thịt bò viên chiên', '1'],
 ['tôm chiên', '1'],
 ['ếch tươi, nước mắm', '1'],
 ['dồi sụn, mắm tôm', '1'],
 ['giấm chua thanh, tiêu xay, đôi khi có mùi thơm nhẹ từ dầu ô liu.', '1'],
 ['mùi thơm thịt bò áp chảo, thoảng mùi tiêu, hành tây sống', '1'],
 ['tôm tươi, cốm chiên thơm', '1'],
 ['rau thơm và thịt, tôm luộc', '1'],
 ['tôm khô, hành phi vàng giòn, rau thơm', '1'],
 ['vị ngọt của tôm và nước sốt thái cay nồng', '1'],
 ['thịt gà, hành phi, rau thơm', '1'],
 ['mùi tôm khô, rau răm, đậu phộng rang', '1'],
 ['hành phi giòn, rau răm, tôm thịt luộc', '1'],
 ['thịt bò áp chảo, rau thơm', '1'],
 ['mùi tiêu xay dậy lên trong nước kho, thơm nồng ấm.', '1'],
 ['thịt ba rọi kho, nước mắm', '1'],
 ['thịt cháy cạnh thơm lừng, quyện mùi mắm', '1'],
 ['thịt luộc, mùi đặc trưng của mắm tôm trộn cùng chanh ớt, hành phi', '1'],
 ['hương mắm kho đặc trưng', '1'],
 ['mùi mắm ruốc quyện với sả ớt, thơm nồng đặc trưng miền trung', '1'],
 ['vị mặn ngọt của nước dừa rim, thịt ba rọi đẫm sốt', '1'],
 ['mùi nước mắm kho quyện cùng với thịt cá', '1'],
 ['thịt cá basa quyện tiêu, nước mắm kho', '1'],
 ['cá thu kho', '1'],
 ['cá trứng chiên, nước mắm me chua ngọt', '1'],
 ['cá bống kho', '1'],
 ['cá bớp kho', '1'],
 ['cá trê chiên giòn, nước mắm xoài xanh', '1'],
 ['cá chiên giòn, rau thơm, nước mắm tỏi ớt', '1'],
 ['cá chiên thơm, rau răm, thoang thoảng mùi xoài xanh', '1'],
 ['hương mắm kho nồng nàng', '1'],
 ['cá chiên thơm, nước mắm xoài cay nồng', '1'],
 ['cá ngừ kho, thơm', '1'],
 ['cá nục kho, tiêu', '1'],
 ['cá nục kho cùng với măng', '1'],
 ['cá điêu hồng chiên sốt cà', '1'],
 ['cá thu sốt cà', '1'],
 ['khô cá đù', '1'],
 ['mùi cay nồng của ớt, rau răm', '1'],
 ['khô cá dứa', '1'],
 ['khô cá lóc', '1'],
 ['mực tươi, ớt chuông, dứa', '1'],
 ['mực tươi, bột chiên', '1'],
 ['nước mắm, mực tươi', '1'],
 ['mực trứng', '1'],
 ['tôm, nước mắm, tiêu', '1'],
 ['mực tươi, thịt heo', '1'],
 ['tép rang, khế', '1'],
 ['tôm, muối rang, ớt', '1'],
 ['sườn heo, ớt chuông, dứa', '1'],
 ['sườn heo, nước mắm, tiêu', '1'],
 ['sườn, ớt', '1'],
 ['cà chua chín, đậu hủ chiên', '1'],
 ['đậu hủ, mắm tôm', '1'],
 ['tôm rim', '1'],
 ['gà kho gừng nồng ấm', '1'],
 ['gà kho đậm mùi sả băm, thơm nồng mùi ớt', '1'],
 ['mùi nước mắm chiên, tỏi phi', '1'],
 ['gừng nồng, mùi vịt kho dậy mùi', '1'],
 ['trứng chiên vàng thơm, hành lá', '1'],
 ['trứng thơm, thoang thoảng vị hến', '1'],
 ['trứng chiên quyện sốt cà, mùi hành lá', '1'],
 ['hành lá quyện trứng chiên', '1'],
 ['thịt bò, rau muống', '1'],
 ['tỏi phi, mùi hoa bí non', '1'],
 ['tỏi phi, rau cải', '1'],
 ['tỏi phi, rau su su', '1'],
 ['tỏi phi, mùi cải ngồng đặc trưng.', '1'],
 ['thịt bò, hành tây, tỏi phi', '1'],
 ['tỏi phi, cải bó xôi chín', '1'],
 ['thịt gà ngọt, lớp da thơm nồng mùi mắm nhĩ', '1'],
 ['tỏi phi, mùi bông hẹ thoang thoảng hăng nhẹ', '1'],
 ['nấm đặc trưng, thoang thoảng dầu hào', '1'],
 ['dầu hào, tỏi phi', '1'],
 ['tôm khô, tiêu, tóp mỡ', '1'],
 ['khổ qua, trứng béo', '1'],
 ['rau muống, tỏi', '1'],
 ['đọt su, tỏi', '1'],
 ['trứng xào, khổ qua', '1'],
 ['thơm mùi tỏi', '1'],
 ['tỏi phi, hẹ non', '1'],
 ['thì là, cần tàu', '1'],
 ['măng chua, thịt cá ngọt, ngò gai', '1'],
 ['tần ô thơm, ngọt thanh', '1'],
 ['cá hú, ngò om, ngò gai', '1'],
 ['thì là nổi bật', '1'],
 ['rau thơm, thì là', '1'],
 ['gạch cua, hành phi', '1'],
 ['lá giang, sả', '1'],
 ['rau om, cần tàu', '1'],
 ['mắm cá, sả, ớt', '1'],
 ['rau đồng, mắm ruốc nhẹ', '1'],
 ['đậu xanh, dừa', '1'],
 ['hương lá sương sáo, nước đường, hột é', '1'],
 ['nước đường, lá dứa', '1'],
 ['sen, thoang thoảng nhãn nhục', '1'],
 ['hoa cúc thanh mát', '1'],
 ['thảo mộc nhẹ, mía lau', '1'],
 ['mùi trà và tắc', '1'],
 ['trà', '1'],
 ['gas', '1'],
 ['nước', '1'],
 ['bia', '1']]

In [17]:
search_values_in_type(df, name_col="current_price")

[['150,000', '37'],
 ['115,000', '9'],
 ['160,000', '8'],
 ['165,000', '7'],
 ['155,000', '6'],
 ['175,000', '6'],
 ['490,000', '4'],
 ['55,000', '4'],
 ['120,000', '4'],
 ['189,000', '4'],
 ['145,000', '3'],
 ['170,000', '3'],
 ['480,000', '3'],
 ['135,000', '2'],
 ['110,000', '2'],
 ['190,000', '2'],
 ['140,000', '2'],
 ['220,000', '2'],
 ['130,000', '2'],
 ['28,000', '2'],
 ['39,000', '2'],
 ['180,000', '1'],
 ['195,000', '1'],
 ['375,000', '1'],
 ['210,000', '1'],
 ['205,000', '1'],
 ['185,000', '1'],
 ['14,000', '1'],
 ['35,000', '1'],
 ['30,000', '1']]

In [10]:
search_values_in_type(df, name_col="number_of_people_eating")

[['2-3 người', '98'],
 ['1 người', '11'],
 ['4-5 người', '7'],
 ['3-4 người', '5'],
 ['1-2 người', '2']]

# TOOL 3

In [34]:
search_values_in_type(df, "type_of_food")

[['món cá', '16'],
 ['món khai vị', '12'],
 ['món ăn chơi', '11'],
 ['món rau', '11'],
 ['món gỏi', '10'],
 ['món gà, vịt & trứng', '9'],
 ['món tôm & mực', '9'],
 ['món xào', '8'],
 ['nước mát nhà làm', '8'],
 ['lẩu', '7'],
 ['món thịt', '7'],
 ['món sườn & đậu hũ', '5'],
 ['món canh', '4'],
 ['các loại khô', '3'],
 ['tráng miệng', '3']]

In [40]:
def search_type_category_and_people(df: pd.DataFrame, col_1: str, num_people: str):
    # normalize for case-insensitive matching
    mask_type = df["type_of_food"].str.lower().str.contains(col_1.lower(), na=False)
    mask_people = df["number_of_people_eating"].str.contains(num_people, na=False)
    # filter dataframe
    result = df[mask_type].reset_index(drop=True)

    return result

# Example usage
filtered_df = search_type_category_and_people(df, "món khai vị", "1")
filtered_df

,ID,type_of_food,name_of_food,how_to_prepare,main_ingredients,taste,outstanding_fragrance,current_price,number_of_people_eating
0,1,MÓN KHAI VỊ,Bánh xèo,"Đổ bột gạo pha nước cốt dừa, chiên vàng giòn c...","Bột gạo, tôm, thịt ba chỉ, giá đỗ,...",Đồ béo,Thơm và béo của nước cốt dừa hoà quyện cùng to...,"145,000",2-3 người
1,2,MÓN KHAI VỊ,Bánh khọt nước dừa,"Đổ bột gạo pha nước cốt dừa vào khuôn nhỏ, chi...","Bột gạo, nước cốt dừa, tôm",Đồ béo,Thơm và béo của nước cốt dừa hoà quyện cùng to...,"145,000",2-3 người
2,3,MÓN KHAI VỊ,Hến xúc bánh đa,"Hến xào hành, rau răm, ăn kèm bánh đa","Hến, rau răm, bánh đa","Đồ mặn, cay","Vị ngọt béo tự nhiên của hến, cay nhẹ của ớt v...","155,000",1-2 người
3,4,MÓN KHAI VỊ,Mực chiên giòn,"Mực tẩm bột chiên xù, chiên vàng","Mực, bột chiên",Đồ béo,"Mực tươi, béo của bột chiên giòn","175,000",2-3 người
4,5,MÓN KHAI VỊ,Cơm cháy mỡ hành chà bông,"Cơm cháy chiên giòn, rưới mỡ hành, rắc chà bông","Gạo, chà bông, hành lá",Đồ mặn,"Thơm mỡ hành, chà bông","150,000",2-3 người
5,6,MÓN KHAI VỊ,Sụn gà rang muối,"Sụn gà chiên giòn, rang với muối Hong Kong","Sụn gà, bột muối rang","Đồ mặn, béo nhẹ",Thơm mùi muối rang,"155,000",1-2 người
6,7,MÓN KHAI VỊ,Chả mực Hạ Long,"Mực giã tay, chiên vàng","Mực, gia vị",Đồ mặn,Mực tươi,"155,000",2-3 người
7,8,MÓN KHAI VỊ,Ốc bươu nhồi thịt,"Ốc bươu nhồi thịt băm, hấp sả","Ốc bươu, thịt băm, sả",Đồ mặn,"Ốc tươi, thơm sả, tiêu","165,000",2-3 người
8,9,MÓN KHAI VỊ,Sụn gà chiên nước mắm,"Sụn gà chiên giòn, sốt nước mắm tỏi ớt","Sụn gà, nước mắm",Đồ mặn,Thơm nước mắm tỏi ớt,"155,000",2-3 người
9,10,MÓN KHAI VỊ,Tôm bọc cốm xanh,"Tôm quết bột, bọc cốm xanh, chiên giòn","Tôm tươi, cốm xanh",Đồ béo,"Tôm tươi, cốm chiên thơm","165,000",2-3 người
10,11,MÓN KHAI VỊ,Chả giò hải sản,"Hải sản băm cuốn bánh tráng, chiên vàng","Hải sản băm, bánh tráng",Đồ béo,Hải sản tươi,"165,000",2-3 người
11,12,MÓN KHAI VỊ,Cơm cháy chảo kho quẹt,"Cơm chiên phồng, ăn kèm kho quẹt tôm khô","Cơm, tôm khô, thịt ba chỉ, chà bông",Đồ mặn,"Kho quẹt, mỡ hành","155,000",2-3 người

In [47]:
import pandas as pd

def search_type_category_and_people(df: pd.DataFrame, col_1: str, num_people: int):
    
    if 0 < num_people < 10:
        col_1 = col_1.lower()

        mask_text = df[
            df.columns[1:]
        ].apply(lambda col: col.astype(str).str.lower().str.contains(col_1, na=False))

        mask_any = mask_text.any(axis=1)

        mask_people = df["number_of_people_eating"].str.contains(str(num_people), na=False)

        result = df[mask_any & mask_people].reset_index(drop=True)

        return result
    else:
        print('input error')

df_fil = search_type_category_and_people(df, "cay", 2)
df_fil

,ID,type_of_food,name_of_food,how_to_prepare,main_ingredients,taste,outstanding_fragrance,current_price,number_of_people_eating
0,3,MÓN KHAI VỊ,Hến xúc bánh đa,"Hến xào hành, rau răm, ăn kèm bánh đa","Hến, rau răm, bánh đa","Đồ mặn, cay","Vị ngọt béo tự nhiên của hến, cay nhẹ của ớt v...","155,000",1-2 người
1,26,MÓN GỎI,Gỏi mực chua cay,"Mực luộc chín vừa, cắt khoanh; trộn với hành t...","Mực tươi, hành tây, cà rốt, rau răm, ớt, nước ...","Đồ chua, cay, ngọt","Mùi cay nồng của ớt, rau răm","160,000",2-3 người
2,29,MÓN GỎI,Gỏi tôm sốt thái,Tôm (sống hoặc chín) trộn cùng nước sốt Thái (...,"Tôm tươi, ớt, chanh, nước sốt thái, xoài xanh",Đồ chua cay,Vị ngọt của tôm và nước sốt thái cay nồng,"175,000",2-3 người
3,44,MÓN CÁ,Cá trứng chiên mắm me,"Cá trứng chiên giòn, chan sốt me chua ngọt mặn...","Cá trứng, me, đường, ớt, nước mắm","Đồ béo, mặn, chua ngọt","Cá trứng chiên, nước mắm me chua ngọt","160,000",2-3 người
4,51,MÓN CÁ,Cá thu chiên mắm xoài,"Cá thu cắt khoanh chiên vàng, rưới sốt mắm xoà...","Cá thu, xoài xanh, nước mắm, ớt","Đồ béo, mặn, chua ngọt","Cá chiên thơm, nước mắm xoài cay nồng","170,000",2-3 người
5,68,MÓN TÔM & MỰC,Tôm rang muối cay,"Tôm chiên giòn, rang muối ớt","Tôm, muối, ớt","Đồ mặn, cay nhẹ","Tôm, muối rang, ớt","190,000",2-3 người
6,71,MÓN SƯỜN & ĐẬU HŨ,Sườn cọng chiên muối ớt,"Sườn chiên giòn, rang muối ớt","Sườn cọng, muối ớt","Đồ mặn, cay nhẹ","Sườn, ớt","205,000",2-3 người

In [ ]:
import pandas as pd

def search_type_category_and_people(df: pd.DataFrame, value_type_of_food: str, value_option: str, num_people: int):
    
    # value_type_of_food in ('món cá', 'món khai vị', 'món ăn chơi', 'món rau', 'món gỏi',
    #    'món gà, vịt & trứng', 'món tôm & mực', 'món xào',
    #    'nước mát nhà làm', 'lẩu', 'món thịt', 'món sườn & đậu hũ',
    #    'món canh', 'các loại khô', 'tráng miệng')
    
    # value_option là yêu cầu khách hàng
    
    # num_people là số lượng người ăn mà khách yêu cầu nếu không có thể thay đổi (1,2,3,4,5,6,7)
    
    value_option = value_option.lower()
    # 🔹 1. Hold fixed type_of_food filter
    mask_type = df["type_of_food"].str.lower().str.contains(value_type_of_food.lower(), na=False)

    # 🔹 2. Search value_option across other columns (excluding type_of_food itself)
    search_cols = df.columns.drop(["type_of_food", "number_of_people_eating"])

    mask_text = df[search_cols].apply(
        lambda col: col.astype(str).str.lower().str.contains(value_option.lower(), na=False)
    )

    mask_any = mask_text.any(axis=1)
    
    mask_people = df["number_of_people_eating"].str.contains(str(num_people), na=False)

    # 🔹 3. Combine filters
    result = df[mask_type & mask_any & mask_people].reset_index(drop=True)

    return result

df_fil = search_type_category_and_people(df, "MÓN CÁ", "mặn", 2)
df_fil

,ID,type_of_food,name_of_food,how_to_prepare,main_ingredients,taste,outstanding_fragrance,current_price,number_of_people_eating
0,41,MÓN CÁ,Cá lóc kho tộ,"Cá lóc cắt khúc, ướp mắm, tiêu, đường, kho tro...","Cá lóc, nước mắm, đường, tiêu, hành tỏi",Đồ mặn,Mùi nước mắm kho quyện cùng với thịt cá,"140,000",2-3 người
1,42,MÓN CÁ,Cá basa kho tộ,"Cá basa béo, kho cùng nước mắm, đường, tiêu đế...","Cá basa, nước mắm, đường, tiêu",Đồ mặn,"Thịt cá basa quyện tiêu, nước mắm kho","140,000",2-3 người
2,43,MÓN CÁ,Cá thu kho tộ,"Cá thu cắt khoanh, ướp gia vị, kho trong nồi đ...","Cá thu, nước mắm, đường, tiêu",Đồ mặn,Cá thu kho,"170,000",2-3 người
3,44,MÓN CÁ,Cá trứng chiên mắm me,"Cá trứng chiên giòn, chan sốt me chua ngọt mặn...","Cá trứng, me, đường, ớt, nước mắm","Đồ béo, mặn, chua ngọt","Cá trứng chiên, nước mắm me chua ngọt","160,000",2-3 người
4,45,MÓN CÁ,Cá bống trứng kho tiêu,Cá bống trứng kho tiêu,"Cá bống trứng, nước mắm, đường, tiêu",Đồ mặn,Cá bống kho,"170,000",2-3 người
5,46,MÓN CÁ,Cá bớp kho tộ,"Cá bớp cắt khúc, kho nước mắm đường, thêm hành...","Cá bớp, nước mắm, đường, tiêu, hành tỏi",Đồ mặn,Cá bớp kho,"175,000",2-3 người
6,47,MÓN CÁ,Cá trê chiên mắm xoài,"Cá trê chiên giòn, rưới sốt mắm pha xoài băm c...","Cá trê, xoài xanh, nước mắm, đường, ớt","Đồ béo, mặn ngọt","Cá trê chiên giòn, nước mắm xoài xanh","150,000",2-3 người
7,48,MÓN CÁ,Cá diêu hồng chiên xù cuốn bánh tráng,"Cá diêu hồng chiên xù nguyên con, ăn kèm bánh ...","Cá diêu hồng, bánh tráng, rau sống, nước mắm c...","Đồ mặn, chua ngọt","Cá chiên giòn, rau thơm, nước mắm tỏi ớt","220,000",2-3 người
8,49,MÓN CÁ,Cá sặc trộn xoài,"Cá sặc phơi khô chiên giòn, xé nhỏ, trộn với x...","Cá sặc khô, xoài xanh, rau răm, ớt","Đồ béo, mặn ngọt","Cá chiên thơm, rau răm, thoang thoảng mùi xoài...","150,000",2-3 người
9,50,MÓN CÁ,Mắm kho miền Tây,"Mắm miền tây nấu với nước, thêm thịt ba rọi, t...","Mắm cá linh/cá sặc, thịt ba rọi, tôm",Đồ mặn,Hương mắm kho nồng nàng,"150,000",2-3 người
10,51,MÓN CÁ,Cá thu chiên mắm xoài,"Cá thu cắt khoanh chiên vàng, rưới sốt mắm xoà...","Cá thu, xoài xanh, nước mắm, ớt","Đồ béo, mặn, chua ngọt","Cá chiên thơm, nước mắm xoài cay nồng","170,000",2-3 người
11,52,MÓN CÁ,Cá ngừ kho thơm,"Cá ngừ kho cùng thơm (dứa), hành tỏi, gia vị m...","Cá ngừ, thơm, nước mắm, hành tỏi",Đồ mặn,"Cá ngừ kho, thơm","150,000",2-3 người
12,53,MÓN CÁ,Cá nục kho khô,"Cá nục kho liu riu với mắm, đường, tiêu đến kh...","Cá nục, măng chua, nước mắm, ớt",Đồ mặn,"Cá nục kho, tiêu","150,000",2-3 người
13,54,MÓN CÁ,Cá nục kho măng,"Cá nục kho cùng măng chua, gia vị mắm, đường, ớt","Cá nục, măng chua, nước mắm, ớt",Đồ mặn,Cá nục kho cùng với măng,"150,000",2-3 người
14,55,MÓN CÁ,Cá điêu hồng chiên sốt cà,"Cá điêu hồng chiên vàng, rưới sốt cà chua xào ...","Cá điêu hồng, cà chua, hành tỏi","Đồ mặn, chua ngọt",Cá điêu hồng chiên sốt cà,"150,000",2-3 người
15,56,MÓN CÁ,Cá thu sốt cà,"Cá thu cắt khoanh, chiên sơ, rim cùng sốt cà chua","Cá thu, cà chua, hành tỏi","Đồ mặn, chua ngọt",Cá thu sốt cà,"175,000",2-3 người

In [ ]:
import pandas as pd
from toolhelper import CategorySearch

# df = pd.DataFrame("../store/comque_new.csv")

d:\langgraph_re_act_agent\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm